---
title: "Plots"
author: "Arthur F. Rossignol"
date: "17.07.2024"
output:
  html_document:
    toc: yes
  pdf_document: default
  word_document:
    toc: yes
---

```{r setup, include = FALSE}
knitr::opts_chunk$set(echo = F)
library(plotly)
library(latex2exp)
library(extrafont)
library(viridisLite)
library(wesanderson)
library(runMCMCbtadjust)
library(nimble)
library(coda)
library(rjags)
library(robust)
library(fGarch)
library(Rfast)

adjust_scale <- function(x) {
  return(ceiling(x / 10^(ceiling(log10(x)) - 1)) * 10^(ceiling(log10(x)) - 1))
}

AIC <- function(AIC_o_o, AIC_i_o, AIC_s_o, AIC_o_i, AIC_o_s, AIC_i_i, AIC_s_i, AIC_i_s, AIC_s_s) {
  r <- length(AIC_o_o)
  all_AIC <- matrix(0, r, 9)
  all_AIC[, 1] <- AIC_o_o
  all_AIC[, 2] <- AIC_i_o
  all_AIC[, 3] <- AIC_s_o
  all_AIC[, 4] <- AIC_o_i
  all_AIC[, 5] <- AIC_o_s
  all_AIC[, 6] <- AIC_i_i
  all_AIC[, 7] <- AIC_s_i
  all_AIC[, 8] <- AIC_i_s
  all_AIC[, 9] <- AIC_s_s
  model_best_AIC <- rep(0, r)
  for (k in 1:r) {
    model_best_AIC[k] <- which.min(all_AIC[k, ])
  }
  table_model_best_AIC <- table(factor(model_best_AIC, levels = c(1, 2, 3, 4, 5, 6, 7, 8, 9)))
  delta_AIC <- matrix(0, r, 9)
  for (i in 1:r) {
    for (j in 1:9) {
      delta_AIC[i, j] <- abs(all_AIC[i, j] - all_AIC[i, model_best_AIC[i]])
    }
  }
  return(list("table" = table_model_best_AIC, "delta" = delta_AIC))
}

BIC <- function(BIC_o_o, BIC_i_o, BIC_s_o, BIC_o_i, BIC_o_s, BIC_i_i, BIC_s_i, BIC_i_s, BIC_s_s) {
  r <- length(BIC_o_o)
  all_BIC <- matrix(0, r, 9)
  all_BIC[, 1] <- BIC_o_o
  all_BIC[, 2] <- BIC_i_o
  all_BIC[, 3] <- BIC_s_o
  all_BIC[, 4] <- BIC_o_i
  all_BIC[, 5] <- BIC_o_s
  all_BIC[, 6] <- BIC_i_i
  all_BIC[, 7] <- BIC_s_i
  all_BIC[, 8] <- BIC_i_s
  all_BIC[, 9] <- BIC_s_s
  model_best_BIC <- rep(0, r)
  for (k in 1:r) {
    model_best_BIC[k] <- which.min(all_BIC[k, ])
  }
  table_model_best_BIC <- table(factor(model_best_BIC, levels = c(1, 2, 3, 4, 5, 6, 7, 8, 9)))
  delta_BIC <- matrix(0, r, 9)
  for (i in 1:r) {
    for (j in 1:9) {
      delta_BIC[i, j] <- abs(all_BIC[i, j] - all_BIC[i, model_best_BIC[i]])
    }
  }
  return(list("table" = table_model_best_BIC, "delta" = delta_BIC))
}

plot_results <- function(path, sigma, phi) {

  par(family = "Times New Roman")
    
  r <- 1000
    
  m_A <- 2
  m_B <- 1
  
  log_sigma_A <- log(sigma)
  log_sigma_B <- log(sigma)
  log_phi <- log(phi)
  
  load(path)
  
  m_A_o_o <- results.to.plot$o_o$m_A
  m_A_i_o <- results.to.plot$i_o$m_A
  m_A_s_o <- results.to.plot$s_o$m_A
  m_A_o_i <- results.to.plot$o_i$m_A
  m_A_o_s <- results.to.plot$o_s$m_A
  m_A_i_i <- results.to.plot$i_i$m_A
  m_A_s_i <- results.to.plot$s_i$m_A
  m_A_i_s <- results.to.plot$i_s$m_A
  m_A_s_s <- results.to.plot$s_s$m_A
  
  m_B_o_o <- results.to.plot$o_o$m_B
  m_B_i_o <- results.to.plot$i_o$m_B
  m_B_s_o <- results.to.plot$s_o$m_B
  m_B_o_i <- results.to.plot$o_i$m_B
  m_B_o_s <- results.to.plot$o_s$m_B
  m_B_i_i <- results.to.plot$i_i$m_B
  m_B_s_i <- results.to.plot$s_i$m_B
  m_B_i_s <- results.to.plot$i_s$m_B
  m_B_s_s <- results.to.plot$s_s$m_B
  
  log_sigma_A_i_o <- results.to.plot$i_o$log_sigma_A
  log_sigma_A_s_o <- results.to.plot$s_o$log_sigma_A
  log_sigma_A_i_i <- results.to.plot$i_i$log_sigma_A
  log_sigma_A_s_i <- results.to.plot$s_i$log_sigma_A
  log_sigma_A_i_s <- results.to.plot$i_s$log_sigma_A
  log_sigma_A_s_s <- results.to.plot$s_s$log_sigma_A
  
  log_sigma_B_o_i <- results.to.plot$o_i$log_sigma_B
  log_sigma_B_o_s <- results.to.plot$o_s$log_sigma_B
  log_sigma_B_i_i <- results.to.plot$i_i$log_sigma_B
  log_sigma_B_s_i <- results.to.plot$s_i$log_sigma_B
  log_sigma_B_i_s <- results.to.plot$i_s$log_sigma_B
  log_sigma_B_s_s <- results.to.plot$s_s$log_sigma_B
  
  log_phi_s_o <- results.to.plot$s_o$log_phi
  log_phi_o_s <- results.to.plot$o_s$log_phi
  log_phi_s_i <- results.to.plot$s_i$log_phi
  log_phi_i_s <- results.to.plot$i_s$log_phi
  log_phi_s_s <- results.to.plot$s_s$log_phi
  
  AIC_o_o <- results.to.plot$o_o$AIC
  AIC_i_o <- results.to.plot$i_o$AIC
  AIC_s_o <- results.to.plot$s_o$AIC
  AIC_o_i <- results.to.plot$o_i$AIC
  AIC_o_s <- results.to.plot$o_s$AIC
  AIC_i_i <- results.to.plot$i_i$AIC
  AIC_s_i <- results.to.plot$s_i$AIC
  AIC_i_s <- results.to.plot$i_s$AIC
  AIC_s_s <- results.to.plot$s_s$AIC
  
  BIC_o_o <- results.to.plot$o_o$BIC
  BIC_i_o <- results.to.plot$i_o$BIC
  BIC_s_o <- results.to.plot$s_o$BIC
  BIC_o_i <- results.to.plot$o_i$BIC
  BIC_o_s <- results.to.plot$o_s$BIC
  BIC_i_i <- results.to.plot$i_i$BIC
  BIC_s_i <- results.to.plot$s_i$BIC
  BIC_i_s <- results.to.plot$i_s$BIC
  BIC_s_s <- results.to.plot$s_s$BIC
  
  #### Plot parameters ####
  
  par(mfrow = c(6, 4), las = 1)
  
  col = rev(wes_palette("Zissou1", 9, type = "continuous"))
  
  #### Boxplots of estimates of m_A ####
  
  par(mar = c(2.5, 2.5, 2, 0.5))
  boxplot(m_A_s_s$estimates, 
          m_A_i_s$estimates, 
          m_A_s_i$estimates, 
          m_A_i_i$estimates,
          m_A_o_s$estimates, 
          m_A_o_i$estimates, 
          m_A_s_o$estimates, 
          m_A_i_o$estimates, 
          m_A_o_o$estimates,
          names = c(latex2exp::TeX(r'($\textbf{s.s}$)'), 
                    latex2exp::TeX(r'($\textbf{i.s}$)'), 
                    latex2exp::TeX(r'($\textbf{s.i}$)'), 
                    latex2exp::TeX(r'($\textbf{i.i}$)'), 
                    latex2exp::TeX(r'($\textbf{o.s}$)'), 
                    latex2exp::TeX(r'($\textbf{o.i}$)'), 
                    latex2exp::TeX(r'($\textbf{s.o}$)'), 
                    latex2exp::TeX(r'($\textbf{i.o}$)'), 
                    latex2exp::TeX(r'($\textbf{o.o}$)')),
          main = latex2exp::TeX(r'(\textbf{(1a)}  $\hat{\textit{m}}_A$ – estimates                  )'), 
          col = "grey",
          las = 1, 
          outline = F, 
          boxwex = 0.8, 
          horizontal = TRUE,
          cex.axis = 1.2,         
          cex.names = 1.2,
          cex.main = 1.3)
  abline(v = m_A, col = "red", lwd = 1.5, lty = 3)
  
  #### Barplots of absolute biases of m_A ####
  
  par(mar = c(2.5, 2.5, 2, 3))
  barplot(c(abs(m_A_s_s$mean_bias), 
            abs(m_A_i_s$mean_bias), 
            abs(m_A_s_i$mean_bias), 
            abs(m_A_i_i$mean_bias), 
            abs(m_A_o_s$mean_bias),
            abs(m_A_o_i$mean_bias), 
            abs(m_A_s_o$mean_bias), 
            abs(m_A_i_o$mean_bias), 
            abs(m_A_o_o$mean_bias)),
          names = c(latex2exp::TeX(r'($\textbf{s.s}$)'), 
                    latex2exp::TeX(r'($\textbf{i.s}$)'), 
                    latex2exp::TeX(r'($\textbf{s.i}$)'), 
                    latex2exp::TeX(r'($\textbf{i.i}$)'), 
                    latex2exp::TeX(r'($\textbf{o.s}$)'), 
                    latex2exp::TeX(r'($\textbf{o.i}$)'), 
                    latex2exp::TeX(r'($\textbf{s.o}$)'), 
                    latex2exp::TeX(r'($\textbf{i.o}$)'), 
                    latex2exp::TeX(r'($\textbf{o.o}$)')),
          col = "grey", 
          main = latex2exp::TeX(r'(\textbf{(1b)}  $\hat{\textit{m}}_A$ – absolute bias )'), 
          las = 1, 
          horiz = T,
          xlim = c(0, adjust_scale(max(c(abs(m_A_s_s$mean_bias), 
                                         abs(m_A_i_s$mean_bias), 
                                         abs(m_A_s_i$mean_bias), 
                                         abs(m_A_i_i$mean_bias), 
                                         abs(m_A_o_s$mean_bias), 
                                         abs(m_A_o_i$mean_bias), 
                                         abs(m_A_s_o$mean_bias), 
                                         abs(m_A_i_o$mean_bias), 
                                         abs(m_A_o_o$mean_bias))))),
          cex.axis = 1.2,         
          cex.names = 1.2,
          cex.main = 1.4)
  box()
  mtext(m_A_o_o$bias_pvalue_lmrob, side = 4, line = 0.7, at = 10.15, cex = 0.7)
  mtext(m_A_o_o$bias_magnitude, side = 4, line = 2.3, at = 10.225, cex = 0.7)
  mtext(m_A_i_o$bias_pvalue_lmrob, side = 4, line = 0.7, at = 8.875, cex = 0.7)
  mtext(m_A_i_o$bias_magnitude, side = 4, line = 2.3, at = 9.0775, cex = 0.7)
  mtext(m_A_s_o$bias_pvalue_lmrob, side = 4, line = 0.7, at = 7.725, cex = 0.7)
  mtext(m_A_s_o$bias_magnitude, side = 4, line = 2.3, at = 7.865, cex = 0.7)
  mtext(m_A_o_i$bias_pvalue_lmrob, side = 4, line = 0.7, at = 6.5125, cex = 0.7)
  mtext(m_A_o_i$bias_magnitude, side = 4, line = 2.3, at = 6.6525, cex = 0.7)
  mtext(m_A_o_s$bias_pvalue_lmrob, side = 4, line = 0.7, at = 5.3, cex = 0.7)
  mtext(m_A_o_s$bias_magnitude, side = 4, line = 2.3, at = 5.44, cex = 0.7)
  mtext(m_A_i_i$bias_pvalue_lmrob, side = 4, line = 0.7, at = 4.0875, cex = 0.7)
  mtext(m_A_i_i$bias_magnitude, side = 4, line = 2.3, at = 4.2275, cex = 0.7)
  mtext(m_A_s_i$bias_pvalue_lmrob, side = 4, line = 0.7, at = 2.875, cex = 0.7)
  mtext(m_A_s_i$bias_magnitude, side = 4, line = 2.3, at = 3.015, cex = 0.7)
  mtext(m_A_i_s$bias_pvalue_lmrob, side = 4, line = 0.7, at = 1.6625, cex = 0.7)
  mtext(m_A_i_s$bias_magnitude, side = 4, line = 2.3, at = 1.8025, cex = 0.7)
  mtext(m_A_s_s$bias_pvalue_lmrob, side = 4, line = 0.7, at = 0.45, cex = 0.7)
  mtext(m_A_s_s$bias_magnitude, side = 4, line = 2.3, at = 0.59, cex = 0.7)
  
  #### Barplots of coverage rates of m_A ####
  
  par(mar = c(2.5, 3.5, 2, 0.7))
  table <- data.frame(m_A_o_o$CR_neg_pos,
                      m_A_i_o$CR_neg_pos,
                      m_A_s_o$CR_neg_pos,
                      m_A_o_i$CR_neg_pos,
                      m_A_o_s$CR_neg_pos,
                      m_A_i_i$CR_neg_pos,
                      m_A_s_i$CR_neg_pos,
                      m_A_i_s$CR_neg_pos,
                      m_A_s_s$CR_neg_pos)
  table <- as.matrix(table)
  barplot(table[, order(ncol(table):1)], col = c("grey", "grey"), 
          density = c(1000, 40),
          names.arg = c(latex2exp::TeX(r'($\textbf{s.s}$)'), 
                        latex2exp::TeX(r'($\textbf{i.s}$)'), 
                        latex2exp::TeX(r'($\textbf{s.i}$)'), 
                        latex2exp::TeX(r'($\textbf{i.i}$)'), 
                        latex2exp::TeX(r'($\textbf{o.s}$)'), 
                        latex2exp::TeX(r'($\textbf{o.i}$)'), 
                        latex2exp::TeX(r'($\textbf{s.o}$)'), 
                        latex2exp::TeX(r'($\textbf{i.o}$)'), 
                        latex2exp::TeX(r'($\textbf{o.o}$)')),
          axes = T, 
          horiz = T, 
          main = latex2exp::TeX(r'( \textbf{(1c)}  $\hat{\textit{m}}_A$ – coverage rate      )'), 
          xlim = c(0, 1),
          cex.axis = 1.2,         
          cex.names = 1.2,
          cex.main = 1.4)
  box()
  mtext(m_A_o_o$CR_pvalue, side = 4, line = 0.7, at = 10.15, cex = 0.7)
  mtext(m_A_o_o$CR_magnitude, side = 4, line = 2.3, at = 10.29, cex = 0.7)
  mtext(m_A_i_o$CR_pvalue, side = 4, line = 0.7, at = 8.875, cex = 0.7)
  mtext(m_A_i_o$CR_magnitude, side = 4, line = 2.3, at = 9.0775, cex = 0.7)
  mtext(m_A_s_o$CR_pvalue, side = 4, line = 0.7, at = 7.725, cex = 0.7)
  mtext(m_A_s_o$CR_magnitude, side = 4, line = 2.3, at = 7.865, cex = 0.7)
  mtext(m_A_o_i$CR_pvalue, side = 4, line = 0.7, at = 6.5125, cex = 0.7)
  mtext(m_A_o_i$CR_magnitude, side = 4, line = 2.3, at = 6.6525, cex = 0.7)
  mtext(m_A_o_s$CR_pvalue, side = 4, line = 0.7, at = 5.3, cex = 0.7)
  mtext(m_A_o_s$CR_magnitude, side = 4, line = 2.3, at = 5.44, cex = 0.7)
  mtext(m_A_i_i$CR_pvalue, side = 4, line = 0.7, at = 4.0875, cex = 0.7)
  mtext(m_A_i_i$CR_magnitude, side = 4, line = 2.3, at = 4.2275, cex = 0.7)
  mtext(m_A_s_i$CR_pvalue, side = 4, line = 0.7, at = 2.875, cex = 0.7)
  mtext(m_A_s_i$CR_magnitude, side = 4, line = 2.3, at = 3.015, cex = 0.7)
  mtext(m_A_i_s$CR_pvalue, side = 4, line = 0.7, at = 1.6625, cex = 0.7)
  mtext(m_A_i_s$CR_magnitude, side = 4, line = 2.3, at = 1.8025, cex = 0.7)
  mtext(m_A_s_s$CR_pvalue, side = 4, line = 0.7, at = 0.45, cex = 0.7)
  mtext(m_A_s_s$CR_magnitude, side = 4, line = 2.3, at = 0.59, cex = 0.7)
  abline(v = 0.05, col = "red", lwd = 1.5, lty = 3)
  
  #### Barplots of RMSEs of m_A ####
  
  par(mar = c(2.5, 6, 2, 1.5))
  barplot(c(m_A_s_s$RMSE, 
            m_A_i_s$RMSE, 
            m_A_s_i$RMSE, 
            m_A_i_i$RMSE, 
            m_A_o_s$RMSE,
            m_A_o_i$RMSE, 
            m_A_s_o$RMSE, 
            m_A_i_o$RMSE, 
            m_A_o_o$RMSE),
          names = c(latex2exp::TeX(r'($\textbf{s.s}$)'), 
                    latex2exp::TeX(r'($\textbf{i.s}$)'), 
                    latex2exp::TeX(r'($\textbf{s.i}$)'), 
                    latex2exp::TeX(r'($\textbf{i.i}$)'), 
                    latex2exp::TeX(r'($\textbf{o.s}$)'), 
                    latex2exp::TeX(r'($\textbf{o.i}$)'), 
                    latex2exp::TeX(r'($\textbf{s.o}$)'), 
                    latex2exp::TeX(r'($\textbf{i.o}$)'), 
                    latex2exp::TeX(r'($\textbf{o.o}$)')),
          col = "grey", 
          main = latex2exp::TeX(r'(\textbf{(1d)}  $\hat{\textit{m}}_A$ – RMSE      )'), 
          las = 1, 
          horiz = T, 
          xlim = c(0, adjust_scale(max(c(m_A_s_s$RMSE, 
                                         m_A_i_s$RMSE, 
                                         m_A_s_i$RMSE, 
                                         m_A_i_i$RMSE, 
                                         m_A_o_s$RMSE, 
                                         m_A_o_i$RMSE, 
                                         m_A_s_o$RMSE, 
                                         m_A_i_o$RMSE, 
                                         m_A_o_o$RMSE)))),
          cex.axis = 1.2,         
          cex.names = 1.2,
          cex.main = 1.4)
  box()
  
  #### Boxplots of estimates of m_B ####
  
  par(mar = c(2.5, 2.5, 2, 0.5))
  boxplot(m_B_s_s$estimates, 
          m_B_i_s$estimates, 
          m_B_s_i$estimates, 
          m_B_i_i$estimates, 
          m_B_o_s$estimates, 
          m_B_o_i$estimates, 
          m_B_s_o$estimates, 
          m_B_i_o$estimates, 
          m_B_o_o$estimates,
          names = c(latex2exp::TeX(r'($\textbf{s.s}$)'), 
                    latex2exp::TeX(r'($\textbf{i.s}$)'), 
                    latex2exp::TeX(r'($\textbf{s.i}$)'), 
                    latex2exp::TeX(r'($\textbf{i.i}$)'), 
                    latex2exp::TeX(r'($\textbf{o.s}$)'), 
                    latex2exp::TeX(r'($\textbf{o.i}$)'), 
                    latex2exp::TeX(r'($\textbf{s.o}$)'), 
                    latex2exp::TeX(r'($\textbf{i.o}$)'), 
                    latex2exp::TeX(r'($\textbf{o.o}$)')),
          main = latex2exp::TeX(r'(\textbf{(2a)}  $\hat{\textit{m}}_B$ – estimates                  )'), 
          col = "grey",
          las = 1, 
          outline = F, 
          boxwex = 0.8, 
          horizontal = TRUE,
          cex.axis = 1.2,         
          cex.names = 1.2,
          cex.main = 1.3)
  abline(v = m_B, col = "red", lwd = 1.5, lty = 3)
  
  #### Barplots of absolute biases of m_A ####
  
  par(mar = c(2.5, 2.5, 2, 3))
  barplot(c(abs(m_B_s_s$mean_bias), 
            abs(m_B_i_s$mean_bias), 
            abs(m_B_s_i$mean_bias), 
            abs(m_B_i_i$mean_bias), 
            abs(m_B_o_s$mean_bias),
            abs(m_B_o_i$mean_bias), 
            abs(m_B_s_o$mean_bias), 
            abs(m_B_i_o$mean_bias), 
            abs(m_B_o_o$mean_bias)),
          names = c(latex2exp::TeX(r'($\textbf{s.s}$)'), 
                    latex2exp::TeX(r'($\textbf{i.s}$)'), 
                    latex2exp::TeX(r'($\textbf{s.i}$)'), 
                    latex2exp::TeX(r'($\textbf{i.i}$)'), 
                    latex2exp::TeX(r'($\textbf{o.s}$)'), 
                    latex2exp::TeX(r'($\textbf{o.i}$)'), 
                    latex2exp::TeX(r'($\textbf{s.o}$)'), 
                    latex2exp::TeX(r'($\textbf{i.o}$)'), 
                    latex2exp::TeX(r'($\textbf{o.o}$)')),
          col = "grey", 
          main = latex2exp::TeX(r'(\textbf{(2b)}  $\hat{\textit{m}}_B$ – absolute bias )'), 
          las = 1, 
          horiz = T,
          xlim = c(0, adjust_scale(max(c(abs(m_B_s_s$mean_bias), 
                                         abs(m_B_i_s$mean_bias), 
                                         abs(m_B_s_i$mean_bias), 
                                         abs(m_B_i_i$mean_bias), 
                                         abs(m_B_o_s$mean_bias), 
                                         abs(m_B_o_i$mean_bias), 
                                         abs(m_B_s_o$mean_bias), 
                                         abs(m_B_i_o$mean_bias), 
                                         abs(m_B_o_o$mean_bias))))),
          cex.axis = 1.2,         
          cex.names = 1.2,
          cex.main = 1.4)
  box()
  mtext(m_B_o_o$bias_pvalue_lmrob, side = 4, line = 0.7, at = 10.15, cex = 0.7)
  mtext(m_B_o_o$bias_magnitude, side = 4, line = 2.3, at = 10.225, cex = 0.7)
  mtext(m_B_i_o$bias_pvalue_lmrob, side = 4, line = 0.7, at = 8.875, cex = 0.7)
  mtext(m_B_i_o$bias_magnitude, side = 4, line = 2.3, at = 9.0775, cex = 0.7)
  mtext(m_B_s_o$bias_pvalue_lmrob, side = 4, line = 0.7, at = 7.725, cex = 0.7)
  mtext(m_B_s_o$bias_magnitude, side = 4, line = 2.3, at = 7.865, cex = 0.7)
  mtext(m_B_o_i$bias_pvalue_lmrob, side = 4, line = 0.7, at = 6.5125, cex = 0.7)
  mtext(m_B_o_i$bias_magnitude, side = 4, line = 2.3, at = 6.6525, cex = 0.7)
  mtext(m_B_o_s$bias_pvalue_lmrob, side = 4, line = 0.7, at = 5.3, cex = 0.7)
  mtext(m_B_o_s$bias_magnitude, side = 4, line = 2.3, at = 5.44, cex = 0.7)
  mtext(m_B_i_i$bias_pvalue_lmrob, side = 4, line = 0.7, at = 4.0875, cex = 0.7)
  mtext(m_B_i_i$bias_magnitude, side = 4, line = 2.3, at = 4.2275, cex = 0.7)
  mtext(m_B_s_i$bias_pvalue_lmrob, side = 4, line = 0.7, at = 2.875, cex = 0.7)
  mtext(m_B_s_i$bias_magnitude, side = 4, line = 2.3, at = 3.015, cex = 0.7)
  mtext(m_B_i_s$bias_pvalue_lmrob, side = 4, line = 0.7, at = 1.6625, cex = 0.7)
  mtext(m_B_i_s$bias_magnitude, side = 4, line = 2.3, at = 1.8025, cex = 0.7)
  mtext(m_B_s_s$bias_pvalue_lmrob, side = 4, line = 0.7, at = 0.45, cex = 0.7)
  mtext(m_B_s_s$bias_magnitude, side = 4, line = 2.3, at = 0.59, cex = 0.7)
  
  #### Barplots of coverage rates of m_B ####
  
  par(mar = c(2.5, 3.5, 2, 0.7))
  table <- data.frame(m_B_o_o$CR_neg_pos,
                      m_B_i_o$CR_neg_pos,
                      m_B_s_o$CR_neg_pos,
                      m_B_o_i$CR_neg_pos,
                      m_B_o_s$CR_neg_pos,
                      m_B_i_i$CR_neg_pos,
                      m_B_s_i$CR_neg_pos,
                      m_B_i_s$CR_neg_pos,
                      m_B_s_s$CR_neg_pos)
  table <- as.matrix(table)
  barplot(table[, order(ncol(table):1)], 
          col = c("grey", "grey"), 
          density = c(1000, 40),
          names.arg = c(latex2exp::TeX(r'($\textbf{s.s}$)'), 
                        latex2exp::TeX(r'($\textbf{i.s}$)'), 
                        latex2exp::TeX(r'($\textbf{s.i}$)'), 
                        latex2exp::TeX(r'($\textbf{i.i}$)'), 
                        latex2exp::TeX(r'($\textbf{o.s}$)'), 
                        latex2exp::TeX(r'($\textbf{o.i}$)'), 
                        latex2exp::TeX(r'($\textbf{s.o}$)'), 
                        latex2exp::TeX(r'($\textbf{i.o}$)'), 
                        latex2exp::TeX(r'($\textbf{o.o}$)')),
          axes = T, 
          horiz = T, 
          main = latex2exp::TeX(r'( \textbf{(2c)}  $\hat{\textit{m}}_B$ – coverage rate      )'), 
          xlim = c(0, 1),
          cex.axis = 1.2,         
          cex.names = 1.2,
          cex.main = 1.4)
  box()
  mtext(m_B_o_o$CR_pvalue, side = 4, line = 0.7, at = 10.15, cex = 0.7)
  mtext(m_B_o_o$CR_magnitude, side = 4, line = 2.3, at = 10.225, cex = 0.7)
  mtext(m_B_i_o$CR_pvalue, side = 4, line = 0.7, at = 8.875, cex = 0.7)
  mtext(m_B_i_o$CR_magnitude, side = 4, line = 2.3, at = 9.0775, cex = 0.7)
  mtext(m_B_s_o$CR_pvalue, side = 4, line = 0.7, at = 7.725, cex = 0.7)
  mtext(m_B_s_o$CR_magnitude, side = 4, line = 2.3, at = 7.865, cex = 0.7)
  mtext(m_B_o_i$CR_pvalue, side = 4, line = 0.7, at = 6.5125, cex = 0.7)
  mtext(m_B_o_i$CR_magnitude, side = 4, line = 2.3, at = 6.6525, cex = 0.7)
  mtext(m_B_o_s$CR_pvalue, side = 4, line = 0.7, at = 5.3, cex = 0.7)
  mtext(m_B_o_s$CR_magnitude, side = 4, line = 2.3, at = 5.44, cex = 0.7)
  mtext(m_B_i_i$CR_pvalue, side = 4, line = 0.7, at = 4.0875, cex = 0.7)
  mtext(m_B_i_i$CR_magnitude, side = 4, line = 2.3, at = 4.2275, cex = 0.7)
  mtext(m_B_s_i$CR_pvalue, side = 4, line = 0.7, at = 2.875, cex = 0.7)
  mtext(m_B_s_i$CR_magnitude, side = 4, line = 2.3, at = 3.015, cex = 0.7)
  mtext(m_B_i_s$CR_pvalue, side = 4, line = 0.7, at = 1.6625, cex = 0.7)
  mtext(m_B_i_s$CR_magnitude, side = 4, line = 2.3, at = 1.8025, cex = 0.7)
  mtext(m_B_s_s$CR_pvalue, side = 4, line = 0.7, at = 0.45, cex = 0.7)
  mtext(m_B_s_s$CR_magnitude, side = 4, line = 2.3, at = 0.59, cex = 0.7)
  abline(v = 0.05, col = "red", lwd = 1.5, lty = 3)
  
  #### Barplots of RMSEs of m_B ####
  
  par(mar = c(2.5, 6, 2, 1.5))
  barplot(c(m_B_s_s$RMSE, 
            m_B_i_s$RMSE, 
            m_B_s_i$RMSE, 
            m_B_i_i$RMSE, 
            m_B_o_s$RMSE, 
            m_B_o_i$RMSE, 
            m_B_s_o$RMSE, 
            m_B_i_o$RMSE, 
            m_B_o_o$RMSE),
          names = c(latex2exp::TeX(r'($\textbf{s.s}$)'), 
                    latex2exp::TeX(r'($\textbf{i.s}$)'), 
                    latex2exp::TeX(r'($\textbf{s.i}$)'), 
                    latex2exp::TeX(r'($\textbf{i.i}$)'), 
                    latex2exp::TeX(r'($\textbf{o.s}$)'), 
                    latex2exp::TeX(r'($\textbf{o.i}$)'), 
                    latex2exp::TeX(r'($\textbf{s.o}$)'), 
                    latex2exp::TeX(r'($\textbf{i.o}$)'), 
                    latex2exp::TeX(r'($\textbf{o.o}$)')),
          col = "grey", 
          main = latex2exp::TeX(r'(\textbf{(2d)}  $\hat{\textit{m}}_B$ – RMSE      )'), 
          las = 1, 
          horiz = T, 
          xlim = c(0, adjust_scale(max(c(m_B_s_s$RMSE, 
                                         m_B_i_s$RMSE, 
                                         m_B_s_i$RMSE, 
                                         m_B_i_i$RMSE, 
                                         m_B_o_s$RMSE, 
                                         m_B_o_i$RMSE, 
                                         m_B_s_o$RMSE, 
                                         m_B_i_o$RMSE, 
                                         m_B_o_o$RMSE)))),
          cex.axis = 1.2,         
          cex.names = 1.2,
          cex.main = 1.4)
  box()
  
  #### Boxplots of estimates of log(σ_A) ####
  
  par(mar = c(2.5, 2.5, 2, 0.5))
  boxplot(log_sigma_A_s_s$estimates, 
          log_sigma_A_i_s$estimates, 
          log_sigma_A_s_i$estimates, 
          log_sigma_A_i_i$estimates, 
          NULL, 
          NULL, 
          log_sigma_A_s_o$estimates, 
          log_sigma_A_i_o$estimates, 
          NULL,
          names = c(latex2exp::TeX(r'($\textbf{s.s}$)'), 
                    latex2exp::TeX(r'($\textbf{i.s}$)'), 
                    latex2exp::TeX(r'($\textbf{s.i}$)'), 
                    latex2exp::TeX(r'($\textbf{i.i}$)'), 
                    latex2exp::TeX(r'($\textbf{o.s}$)'), 
                    latex2exp::TeX(r'($\textbf{o.i}$)'), 
                    latex2exp::TeX(r'($\textbf{s.o}$)'), 
                    latex2exp::TeX(r'($\textbf{i.o}$)'), 
                    latex2exp::TeX(r'($\textbf{o.o}$)')),
          main = latex2exp::TeX(r'(\textbf{(3a)}  $\log(\hat{\textit{σ}}_A)$ – estimates           )'),
          col = "grey",
          las = 1, 
          outline = F, 
          boxwex = 0.8, 
          horizontal = TRUE,
          cex.axis = 1.2,         
          cex.names = 1.2,
          cex.main = 1.3)
  abline(v = log_sigma_A, col = "red", lwd = 1.5, lty = 3)
  
  #### Barplots of absolute biases of log_sigma_A ####
  
  par(mar = c(2.5, 2.5, 2, 3))
  barplot(c(abs(log_sigma_A_s_s$mean_bias), 
            abs(log_sigma_A_i_s$mean_bias), 
            abs(log_sigma_A_s_i$mean_bias), 
            abs(log_sigma_A_i_i$mean_bias), 
            NaN,
            NaN, 
            abs(log_sigma_A_s_o$mean_bias), 
            abs(log_sigma_A_i_o$mean_bias), 
            NaN),
          names = c(latex2exp::TeX(r'($\textbf{s.s}$)'), 
                    latex2exp::TeX(r'($\textbf{i.s}$)'), 
                    latex2exp::TeX(r'($\textbf{s.i}$)'), 
                    latex2exp::TeX(r'($\textbf{i.i}$)'), 
                    latex2exp::TeX(r'($\textbf{o.s}$)'), 
                    latex2exp::TeX(r'($\textbf{o.i}$)'), 
                    latex2exp::TeX(r'($\textbf{s.o}$)'), 
                    latex2exp::TeX(r'($\textbf{i.o}$)'), 
                    latex2exp::TeX(r'($\textbf{o.o}$)')),
          col = "grey", 
          main = latex2exp::TeX(r'(       \textbf{(3b)}  $\log(\hat{\textit{σ}}_A)$ – absolute bias)'), 
          las = 1, 
          horiz = T,
          xlim = c(0, adjust_scale(max(c(abs(log_sigma_A_s_s$mean_bias), 
                                         abs(log_sigma_A_i_s$mean_bias), 
                                         abs(log_sigma_A_s_i$mean_bias), 
                                         abs(log_sigma_A_i_i$mean_bias), 
                                         abs(log_sigma_A_s_o$mean_bias), 
                                         abs(log_sigma_A_i_o$mean_bias))))),
          cex.axis = 1.2,         
          cex.names = 1.2,
          cex.main = 1.4)
  box()
  mtext(log_sigma_A_i_o$bias_pvalue_lmrob, side = 4, line = 0.7, at = 8.875, cex = 0.7)
  mtext(log_sigma_A_i_o$bias_magnitude, side = 4, line = 2.3, at = 9.0775, cex = 0.7)
  mtext(log_sigma_A_s_o$bias_pvalue_lmrob, side = 4, line = 0.7, at = 7.725, cex = 0.7)
  mtext(log_sigma_A_s_o$bias_magnitude, side = 4, line = 2.3, at = 7.865, cex = 0.7)
  mtext(log_sigma_A_i_i$bias_pvalue_lmrob, side = 4, line = 0.7, at = 4.0875, cex = 0.7)
  mtext(log_sigma_A_i_i$bias_magnitude, side = 4, line = 2.3, at = 4.2275, cex = 0.7)
  mtext(log_sigma_A_s_i$bias_pvalue_lmrob, side = 4, line = 0.7, at = 2.875, cex = 0.7)
  mtext(log_sigma_A_s_i$bias_magnitude, side = 4, line = 2.3, at = 3.015, cex = 0.7)
  mtext(log_sigma_A_i_s$bias_pvalue_lmrob, side = 4, line = 0.7, at = 1.6625, cex = 0.7)
  mtext(log_sigma_A_i_s$bias_magnitude, side = 4, line = 2.3, at = 1.8025, cex = 0.7)
  mtext(log_sigma_A_s_s$bias_pvalue_lmrob, side = 4, line = 0.7, at = 0.45, cex = 0.7)
  mtext(log_sigma_A_s_s$bias_magnitude, side = 4, line = 2.3, at = 0.59, cex = 0.7)
  
  #### Barplots of coverage rates of log(σ_A) ####
  
  par(mar = c(2.5, 3.5, 2, 0.7))
  table <- data.frame(c(NaN, NaN),
                      log_sigma_A_i_o$CR_neg_pos,
                      log_sigma_A_s_o$CR_neg_pos,
                      c(NaN, NaN),
                      c(NaN, NaN),
                      log_sigma_A_i_i$CR_neg_pos,
                      log_sigma_A_s_i$CR_neg_pos,
                      log_sigma_A_i_s$CR_neg_pos,
                      log_sigma_A_s_s$CR_neg_pos)
  table <- as.matrix(table)
  barplot(table[, order(ncol(table):1)], col = c("grey", "grey"), density = c(1000, 40),
          names.arg = c(latex2exp::TeX(r'($\textbf{s.s}$)'), 
                        latex2exp::TeX(r'($\textbf{i.s}$)'), 
                        latex2exp::TeX(r'($\textbf{s.i}$)'), 
                        latex2exp::TeX(r'($\textbf{i.i}$)'), 
                        latex2exp::TeX(r'($\textbf{o.s}$)'), 
                        latex2exp::TeX(r'($\textbf{o.i}$)'), 
                        latex2exp::TeX(r'($\textbf{s.o}$)'), 
                        latex2exp::TeX(r'($\textbf{i.o}$)'), 
                        latex2exp::TeX(r'($\textbf{o.o}$)')),
          axes = T, 
          horiz = T, 
          main = latex2exp::TeX(r'(   \textbf{(3c)}  $\log(\hat{\textit{σ}}_A)$ – coverage rate)'), 
          xlim = c(0, 1),
          cex.axis = 1.2,         
          cex.names = 1.2,
          cex.main = 1.4)
  box()
  mtext(log_sigma_A_i_o$CR_pvalue, side = 4, line = 0.7, at = 8.875, cex = 0.7)
  mtext(log_sigma_A_i_o$CR_magnitude, side = 4, line = 2.3, at = 9.0775, cex = 0.7)
  mtext(log_sigma_A_s_o$CR_pvalue, side = 4, line = 0.7, at = 7.725, cex = 0.7)
  mtext(log_sigma_A_s_o$CR_magnitude, side = 4, line = 2.3, at = 7.865, cex = 0.7)
  mtext(log_sigma_A_i_i$CR_pvalue, side = 4, line = 0.7, at = 4.0875, cex = 0.7)
  mtext(log_sigma_A_i_i$CR_magnitude, side = 4, line = 2.3, at = 4.2275, cex = 0.7)
  mtext(log_sigma_A_s_i$CR_pvalue, side = 4, line = 0.7, at = 2.875, cex = 0.7)
  mtext(log_sigma_A_s_i$CR_magnitude, side = 4, line = 2.3, at = 3.015, cex = 0.7)
  mtext(log_sigma_A_i_s$CR_pvalue, side = 4, line = 0.7, at = 1.6625, cex = 0.7)
  mtext(log_sigma_A_i_s$CR_magnitude, side = 4, line = 2.3, at = 1.8025, cex = 0.7)
  mtext(log_sigma_A_s_s$CR_pvalue, side = 4, line = 0.7, at = 0.45, cex = 0.7)
  mtext(log_sigma_A_s_s$CR_magnitude, side = 4, line = 2.3, at = 0.59, cex = 0.7)
  abline(v = 0.05, col = "red", lwd = 1.5, lty = 3)
  
  #### Barplots of RMSEs of log(σ_A) ####
  
  par(mar = c(2.5, 6, 2, 1.5))
  barplot(c(log_sigma_A_s_s$RMSE, 
            log_sigma_A_i_s$RMSE, 
            log_sigma_A_s_i$RMSE, 
            log_sigma_A_i_i$RMSE, 
            NaN, 
            NaN, 
            log_sigma_A_s_o$RMSE, 
            log_sigma_A_i_o$RMSE, 
            NaN),
          names = c(latex2exp::TeX(r'($\textbf{s.s}$)'), 
                    latex2exp::TeX(r'($\textbf{i.s}$)'), 
                    latex2exp::TeX(r'($\textbf{s.i}$)'), 
                    latex2exp::TeX(r'($\textbf{i.i}$)'), 
                    latex2exp::TeX(r'($\textbf{o.s}$)'), 
                    latex2exp::TeX(r'($\textbf{o.i}$)'), 
                    latex2exp::TeX(r'($\textbf{s.o}$)'), 
                    latex2exp::TeX(r'($\textbf{i.o}$)'), 
                    latex2exp::TeX(r'($\textbf{o.o}$)')),
          col = "grey", 
          main = latex2exp::TeX(r'(  \textbf{(3d)}  $\log(\hat{\textit{σ}}_A)$ – RMSE)'), 
          las = 1, 
          horiz = T, 
          xlim = c(0,  adjust_scale(max(c(log_sigma_A_s_s$RMSE, 
                                          log_sigma_A_i_s$RMSE, 
                                          log_sigma_A_s_i$RMSE, 
                                          log_sigma_A_i_i$RMSE, 
                                          log_sigma_A_s_o$RMSE, 
                                          log_sigma_A_i_o$RMSE)))),
          cex.axis = 1.2,         
          cex.names = 1.2,
          cex.main = 1.4)
  box()
  
  #### Boxplots of estimates of log(σ_B) ####
  
  par(mar = c(2.5, 2.5, 2, 0.5))
  boxplot(log_sigma_B_s_s$estimates, 
          log_sigma_B_i_s$estimates, 
          log_sigma_B_s_i$estimates, 
          log_sigma_B_i_i$estimates, 
          log_sigma_B_o_s$estimates, 
          log_sigma_B_o_i$estimates, 
          NULL, 
          NULL, 
          NULL,
          names = c(latex2exp::TeX(r'($\textbf{s.s}$)'), 
                    latex2exp::TeX(r'($\textbf{i.s}$)'), 
                    latex2exp::TeX(r'($\textbf{s.i}$)'), 
                    latex2exp::TeX(r'($\textbf{i.i}$)'), 
                    latex2exp::TeX(r'($\textbf{o.s}$)'), 
                    latex2exp::TeX(r'($\textbf{o.i}$)'), 
                    latex2exp::TeX(r'($\textbf{s.o}$)'), 
                    latex2exp::TeX(r'($\textbf{i.o}$)'), 
                    latex2exp::TeX(r'($\textbf{o.o}$)')),
          main = latex2exp::TeX(r'(\textbf{(4a)}  $\log(\hat{\textit{σ}}_B)$ – estimates           )'), 
          col = "grey",
          las = 1, 
          outline = F, 
          boxwex = 0.8, 
          horizontal = TRUE,
          cex.axis = 1.2,         
          cex.names = 1.2,
          cex.main = 1.3)
  abline(v = log_sigma_B, col = "red", lwd = 1.5, lty = 3)
  
  #### Barplots of absolute biases of log(σ_B) ####
  
  par(mar = c(2.5, 2.5, 2, 3))
  barplot(c(abs(log_sigma_B_s_s$mean_bias), 
            abs(log_sigma_B_i_s$mean_bias), 
            abs(log_sigma_B_s_i$mean_bias), 
            abs(log_sigma_B_i_i$mean_bias), 
            abs(log_sigma_B_o_s$mean_bias),
            abs(log_sigma_B_o_i$mean_bias), 
            NaN, 
            NaN, 
            NaN),
          names = c(latex2exp::TeX(r'($\textbf{s.s}$)'), 
                    latex2exp::TeX(r'($\textbf{i.s}$)'), 
                    latex2exp::TeX(r'($\textbf{s.i}$)'), 
                    latex2exp::TeX(r'($\textbf{i.i}$)'), 
                    latex2exp::TeX(r'($\textbf{o.s}$)'), 
                    latex2exp::TeX(r'($\textbf{o.i}$)'), 
                    latex2exp::TeX(r'($\textbf{s.o}$)'), 
                    latex2exp::TeX(r'($\textbf{i.o}$)'), 
                    latex2exp::TeX(r'($\textbf{o.o}$)')),
          col = "grey", 
          main = latex2exp::TeX(r'(       \textbf{(4b)}  $\log(\hat{\textit{σ}}_B)$ – absolute bias)'), 
          las = 1,
          horiz = T,
          xlim = c(0, adjust_scale(max(c(abs(log_sigma_B_s_s$mean_bias), 
                                         abs(log_sigma_B_i_s$mean_bias), 
                                         abs(log_sigma_B_s_i$mean_bias), 
                                         abs(log_sigma_B_i_i$mean_bias), 
                                         abs(log_sigma_B_o_s$mean_bias), 
                                         abs(log_sigma_B_o_i$mean_bias))))),
          cex.axis = 1.2,         
          cex.names = 1.2,
          cex.main = 1.4)
  box()
  mtext(log_sigma_B_o_i$bias_pvalue_lmrob, side = 4, line = 0.7, at = 6.5125, cex = 0.7)
  mtext(log_sigma_B_o_i$bias_magnitude, side = 4, line = 2.3, at = 6.6525, cex = 0.7)
  mtext(log_sigma_B_o_s$bias_pvalue_lmrob, side = 4, line = 0.7, at = 5.3, cex = 0.7)
  mtext(log_sigma_B_o_s$bias_magnitude, side = 4, line = 2.3, at = 5.44, cex = 0.7)
  mtext(log_sigma_B_i_i$bias_pvalue_lmrob, side = 4, line = 0.7, at = 4.0875, cex = 0.7)
  mtext(log_sigma_B_i_i$bias_magnitude, side = 4, line = 2.3, at = 4.2275, cex = 0.7)
  mtext(log_sigma_B_s_i$bias_pvalue_lmrob, side = 4, line = 0.7, at = 2.875, cex = 0.7)
  mtext(log_sigma_B_s_i$bias_magnitude, side = 4, line = 2.3, at = 3.015, cex = 0.7)
  mtext(log_sigma_B_i_s$bias_pvalue_lmrob, side = 4, line = 0.7, at = 1.6625, cex = 0.7)
  mtext(log_sigma_B_i_s$bias_magnitude, side = 4, line = 2.3, at = 1.8025, cex = 0.7)
  mtext(log_sigma_B_s_s$bias_pvalue_lmrob, side = 4, line = 0.7, at = 0.45, cex = 0.7)
  mtext(log_sigma_B_s_s$bias_magnitude, side = 4, line = 2.3, at = 0.59, cex = 0.7)
  
  #### Barplots of coverage rates of log(σ_B) ####
  
  par(mar = c(2.5, 3.5, 2, 0.7))
  table <- data.frame(c(NaN, NaN),
                      c(NaN, NaN),
                      c(NaN, NaN),
                      log_sigma_B_o_i$CR_neg_pos,
                      log_sigma_B_o_s$CR_neg_pos,
                      log_sigma_B_i_i$CR_neg_pos,
                      log_sigma_B_s_i$CR_neg_pos,
                      log_sigma_B_i_s$CR_neg_pos,
                      log_sigma_B_s_s$CR_neg_pos)
  table <- as.matrix(table)
  barplot(table[, order(ncol(table):1)], 
          col = c("grey", "grey"), 
          density = c(1000, 40),
          names.arg = c(latex2exp::TeX(r'($\textbf{s.s}$)'), 
                        latex2exp::TeX(r'($\textbf{i.s}$)'), 
                        latex2exp::TeX(r'($\textbf{s.i}$)'), 
                        latex2exp::TeX(r'($\textbf{i.i}$)'), 
                        latex2exp::TeX(r'($\textbf{o.s}$)'), 
                        latex2exp::TeX(r'($\textbf{o.i}$)'), 
                        latex2exp::TeX(r'($\textbf{s.o}$)'), 
                        latex2exp::TeX(r'($\textbf{i.o}$)'), 
                        latex2exp::TeX(r'($\textbf{o.o}$)')),
          axes = T, 
          horiz = T, 
          main = latex2exp::TeX(r'(   \textbf{(4c)}  $\log(\hat{\textit{σ}}_B)$ – coverage rate)'), 
          xlim = c(0, 1),
          cex.axis = 1.2,         
          cex.names = 1.2,
          cex.main = 1.4)
  box()
  mtext(log_sigma_B_o_i$CR_pvalue, side = 4, line = 0.7, at = 6.5125, cex = 0.7)
  mtext(log_sigma_B_o_i$CR_magnitude, side = 4, line = 2.3, at = 6.6525, cex = 0.7)
  mtext(log_sigma_B_o_s$CR_pvalue, side = 4, line = 0.7, at = 5.3, cex = 0.7)
  mtext(log_sigma_B_o_s$CR_magnitude, side = 4, line = 2.3, at = 5.44, cex = 0.7)
  mtext(log_sigma_B_i_i$CR_pvalue, side = 4, line = 0.7, at = 4.0875, cex = 0.7)
  mtext(log_sigma_B_i_i$CR_magnitude, side = 4, line = 2.3, at = 4.2275, cex = 0.7)
  mtext(log_sigma_B_s_i$CR_pvalue, side = 4, line = 0.7, at = 2.875, cex = 0.7)
  mtext(log_sigma_B_s_i$CR_magnitude, side = 4, line = 2.3, at = 3.015, cex = 0.7)
  mtext(log_sigma_B_i_s$CR_pvalue, side = 4, line = 0.7, at = 1.6625, cex = 0.7)
  mtext(log_sigma_B_i_s$CR_magnitude, side = 4, line = 2.3, at = 1.8025, cex = 0.7)
  mtext(log_sigma_B_s_s$CR_pvalue, side = 4, line = 0.7, at = 0.45, cex = 0.7)
  mtext(log_sigma_B_s_s$CR_magnitude, side = 4, line = 2.3, at = 0.59, cex = 0.7)
  abline(v = 0.05, col = "red", lwd = 1.5, lty = 3)
  
  #### Barplots of RMSEs of log(σ_B) ####
  
  par(mar = c(2.5, 6, 2, 1.5))
  barplot(c(log_sigma_B_s_s$RMSE, 
            log_sigma_B_i_s$RMSE, 
            log_sigma_B_s_i$RMSE, 
            log_sigma_B_i_i$RMSE, 
            log_sigma_B_o_s$RMSE, 
            log_sigma_B_o_i$RMSE, 
            NaN, 
            NaN, 
            NaN),
          names = c(latex2exp::TeX(r'($\textbf{s.s}$)'), 
                    latex2exp::TeX(r'($\textbf{i.s}$)'), 
                    latex2exp::TeX(r'($\textbf{s.i}$)'), 
                    latex2exp::TeX(r'($\textbf{i.i}$)'), 
                    latex2exp::TeX(r'($\textbf{o.s}$)'), 
                    latex2exp::TeX(r'($\textbf{o.i}$)'), 
                    latex2exp::TeX(r'($\textbf{s.o}$)'), 
                    latex2exp::TeX(r'($\textbf{i.o}$)'), 
                    latex2exp::TeX(r'($\textbf{o.o}$)')),
          col = "grey", 
          main = latex2exp::TeX(r'(  \textbf{(4d)}  $\log(\hat{\textit{σ}}_B)$ – RMSE)'), 
          las = 1, 
          horiz = T, 
          xlim = c(0,  adjust_scale(max(c(log_sigma_B_s_s$RMSE, 
                                          log_sigma_B_i_s$RMSE, 
                                          log_sigma_B_o_s$RMSE, 
                                          log_sigma_B_s_i$RMSE, 
                                          log_sigma_B_i_i$RMSE, 
                                          log_sigma_B_o_i$RMSE)))),
          cex.axis = 1.2,         
          cex.names = 1.2,
          cex.main = 1.4)
  box()
  
  #### Boxplots of estimates of log(ϕ) ####
  
  par(mar = c(2.5, 2.5, 2, 0.5))
  boxplot(log_phi_s_s$estimates, 
          log_phi_i_s$estimates, 
          log_phi_s_i$estimates, 
          NULL, 
          log_phi_o_s$estimates, 
          NULL, 
          log_phi_s_o$estimates, 
          NULL, 
          NULL,
          names = c(latex2exp::TeX(r'($\textbf{s.s}$)'), 
                    latex2exp::TeX(r'($\textbf{i.s}$)'), 
                    latex2exp::TeX(r'($\textbf{s.i}$)'), 
                    latex2exp::TeX(r'($\textbf{i.i}$)'), 
                    latex2exp::TeX(r'($\textbf{o.s}$)'), 
                    latex2exp::TeX(r'($\textbf{o.i}$)'), 
                    latex2exp::TeX(r'($\textbf{s.o}$)'), 
                    latex2exp::TeX(r'($\textbf{i.o}$)'), 
                    latex2exp::TeX(r'($\textbf{o.o}$)')),
          main = latex2exp::TeX(r'(\textbf{(5a)}  $\log(\hat{\textit{ϕ}})$ – estimates            )'), 
          col = "grey",
          las = 1, 
          outline = F, 
          boxwex = 0.8, 
          horizontal = TRUE,
          cex.axis = 1.2,         
          cex.names = 1.2,
          cex.main = 1.3)
  abline(v = log_phi, col = "red", lwd = 1.5, lty = 3)
  
  #### Barplots of absolute biases of log(ϕ) ####
  
  par(mar = c(2.5, 2.5, 2, 3))
  barplot(c(abs(log_phi_s_s$mean_bias), 
            abs(log_phi_i_s$mean_bias), 
            abs(log_phi_s_i$mean_bias), 
            NaN, 
            abs(log_phi_o_s$mean_bias),
            NaN, 
            abs(log_phi_s_o$mean_bias), 
            NaN, 
            NaN),
          names = c(latex2exp::TeX(r'($\textbf{s.s}$)'), 
                    latex2exp::TeX(r'($\textbf{i.s}$)'), 
                    latex2exp::TeX(r'($\textbf{s.i}$)'), 
                    latex2exp::TeX(r'($\textbf{i.i}$)'), 
                    latex2exp::TeX(r'($\textbf{o.s}$)'), 
                    latex2exp::TeX(r'($\textbf{o.i}$)'), 
                    latex2exp::TeX(r'($\textbf{s.o}$)'), 
                    latex2exp::TeX(r'($\textbf{i.o}$)'), 
                    latex2exp::TeX(r'($\textbf{o.o}$)')),
          col = "grey", 
          main = latex2exp::TeX(r'(     \textbf{(5b)}  $\log(\hat{\textit{ϕ}})$ – absolute bias)'), 
          las = 1, 
          horiz = T,
          xlim = c(0, adjust_scale(max(c(abs(log_phi_s_s$mean_bias), 
                                         abs(log_phi_i_s$mean_bias), 
                                         abs(log_phi_s_i$mean_bias), 
                                         abs(log_phi_o_s$mean_bias), 
                                         abs(log_phi_s_o$mean_bias))))),
          cex.axis = 1.2,
          cex.names = 1.2,
          cex.main = 1.4)
  box()
  mtext(log_phi_s_o$bias_pvalue_lmrob, side = 4, line = 0.7, at = 7.725, cex = 0.7)
  mtext(log_phi_s_o$bias_magnitude, side = 4, line = 2.3, at = 7.865, cex = 0.7)
  mtext(log_phi_o_s$bias_pvalue_lmrob, side = 4, line = 0.7, at = 5.3, cex = 0.7)
  mtext(log_phi_o_s$bias_magnitude, side = 4, line = 2.3, at = 5.44, cex = 0.7)
  mtext(log_phi_s_i$bias_pvalue_lmrob, side = 4, line = 0.7, at = 2.875, cex = 0.7)
  mtext(log_phi_s_i$bias_magnitude, side = 4, line = 2.3, at = 3.015, cex = 0.7)
  mtext(log_phi_i_s$bias_pvalue_lmrob, side = 4, line = 0.7, at = 1.6625, cex = 0.7)
  mtext(log_phi_i_s$bias_magnitude, side = 4, line = 2.3, at = 1.8025, cex = 0.7)
  mtext(log_phi_s_s$bias_pvalue_lmrob, side = 4, line = 0.7, at = 0.45, cex = 0.7)
  mtext(log_phi_s_s$bias_magnitude, side = 4, line = 2.3, at = 0.59, cex = 0.7)
  
  #### Barplots of coverage rates of log(ϕ) ####
  
  par(mar = c(2.5, 3.5, 2, 0.7))
  table <- data.frame(c(NaN, NaN),
                      c(NaN, NaN),
                      log_phi_s_o$CR_neg_pos,
                      c(NaN, NaN),
                      log_phi_o_s$CR_neg_pos,
                      c(NaN, NaN),
                      log_phi_s_i$CR_neg_pos,
                      log_phi_i_s$CR_neg_pos,
                      log_phi_s_s$CR_neg_pos)
  table <- as.matrix(table)
  barplot(table[, order(ncol(table):1)], 
          col = c("grey", "grey"), 
          density = c(1000, 40),
          names.arg = c(latex2exp::TeX(r'($\textbf{s.s}$)'), 
                        latex2exp::TeX(r'($\textbf{i.s}$)'), 
                        latex2exp::TeX(r'($\textbf{s.i}$)'), 
                        latex2exp::TeX(r'($\textbf{i.i}$)'), 
                        latex2exp::TeX(r'($\textbf{o.s}$)'), 
                        latex2exp::TeX(r'($\textbf{o.i}$)'), 
                        latex2exp::TeX(r'($\textbf{s.o}$)'), 
                        latex2exp::TeX(r'($\textbf{i.o}$)'), 
                        latex2exp::TeX(r'($\textbf{o.o}$)')),
          axes = T, 
          horiz = T, 
          main = latex2exp::TeX(r'(  \textbf{(5c)}  $\log(\hat{\textit{ϕ}})$ – coverage rate)'), 
          xlim = c(0, 1),
          cex.axis = 1.2,         
          cex.names = 1.2,
          cex.main = 1.4)
  box()
  mtext(log_phi_s_o$CR_pvalue, side = 4, line = 0.7, at = 7.725, cex = 0.7)
  mtext(log_phi_s_o$CR_magnitude, side = 4, line = 2.3, at = 7.865, cex = 0.7)
  mtext(log_phi_o_s$CR_pvalue, side = 4, line = 0.7, at = 5.3, cex = 0.7)
  mtext(log_phi_o_s$CR_magnitude, side = 4, line = 2.3, at = 5.44, cex = 0.7)
  mtext(log_phi_s_i$CR_pvalue, side = 4, line = 0.7, at = 2.875, cex = 0.7)
  mtext(log_phi_s_i$CR_magnitude, side = 4, line = 2.3, at = 3.015, cex = 0.7)
  mtext(log_phi_i_s$CR_pvalue, side = 4, line = 0.7, at = 1.6625, cex = 0.7)
  mtext(log_phi_i_s$CR_magnitude, side = 4, line = 2.3, at = 1.8025, cex = 0.7)
  mtext(log_phi_s_s$CR_pvalue, side = 4, line = 0.7, at = 0.45, cex = 0.7)
  mtext(log_phi_s_s$CR_magnitude, side = 4, line = 2.3, at = 0.59, cex = 0.7)
  abline(v = 0.05, col = "red", lwd = 1.5, lty = 3)
  
  #### Barplots of RMSEs of log(ϕ) ####
  
  par(mar = c(2.5, 6, 2, 1.5))
  barplot(c(log_phi_s_s$RMSE, 
            log_phi_i_s$RMSE, 
            log_phi_s_i$RMSE, 
            NaN, 
            log_phi_o_s$RMSE, 
            NaN, 
            log_phi_s_o$RMSE, 
            NaN, 
            NaN),
          names = c(latex2exp::TeX(r'($\textbf{s.s}$)'), 
                    latex2exp::TeX(r'($\textbf{i.s}$)'), 
                    latex2exp::TeX(r'($\textbf{s.i}$)'), 
                    latex2exp::TeX(r'($\textbf{i.i}$)'), 
                    latex2exp::TeX(r'($\textbf{o.s}$)'), 
                    latex2exp::TeX(r'($\textbf{o.i}$)'), 
                    latex2exp::TeX(r'($\textbf{s.o}$)'), 
                    latex2exp::TeX(r'($\textbf{i.o}$)'), 
                    latex2exp::TeX(r'($\textbf{o.o}$)')),
          col = "grey", 
          main = latex2exp::TeX(r'( \textbf{(5d)}  $\log(\hat{\textit{ϕ}})$ – RMSE)'), 
          las = 1, 
          horiz = T, 
          xlim = c(0, adjust_scale(max(c(log_phi_s_s$RMSE, 
                                         log_phi_i_s$RMSE, 
                                         log_phi_o_s$RMSE, 
                                         log_phi_s_i$RMSE, 
                                         log_phi_s_o$RMSE)))),
          cex.axis = 1.2,         
          cex.names = 1.2,
          cex.main = 1.4)
  box()
  
  #### Barplots of AIC ####
  
  par(mar = c(2.5, 2.5, 2, 1))
  table_AIC <- AIC(AIC_o_o, 
                   AIC_i_o, 
                   AIC_s_o, 
                   AIC_o_i, 
                   AIC_i_i, 
                   AIC_s_i, 
                   AIC_o_s, 
                   AIC_i_s, 
                   AIC_s_s)$table[c(9, 8, 7, 6, 5, 4, 3, 2, 1)]
  table_AIC <- table_AIC / r * 100
  barplot(table_AIC, names = c(latex2exp::TeX(r'($\textbf{s.s}$)'), 
                               latex2exp::TeX(r'($\textbf{i.s}$)'), 
                               latex2exp::TeX(r'($\textbf{s.i}$)'), 
                               latex2exp::TeX(r'($\textbf{i.i}$)'), 
                               latex2exp::TeX(r'($\textbf{o.s}$)'), 
                               latex2exp::TeX(r'($\textbf{o.i}$)'), 
                               latex2exp::TeX(r'($\textbf{s.o}$)'), 
                               latex2exp::TeX(r'($\textbf{i.o}$)'), 
                               latex2exp::TeX(r'($\textbf{o.o}$)')),
          col = "grey", 
          las = 1, 
          horiz = T, 
          xlim = c(0, 100), 
          main = latex2exp::TeX(r'(\textbf{(6a)}  AIC – proportion as b.m. )'),
          cex.axis = 1.2,         
          cex.names = 1.2,
          cex.main = 1.3)
  box()
  
  #### Boxplots of AIC ####
  
  par(mar = c(2.5, 2.5, 2, 1))
  boxplot((1 + AIC(AIC_o_o, 
                   AIC_i_o, 
                   AIC_s_o, 
                   AIC_o_i, 
                   AIC_o_s, 
                   AIC_i_i, 
                   AIC_s_i, 
                   AIC_i_s, 
                   AIC_s_s)$delta[, c(9, 8, 7, 6, 5, 4, 3, 2, 1)]),
          names = c(latex2exp::TeX(r'($\textbf{s.s}$)'), 
                    latex2exp::TeX(r'($\textbf{i.s}$)'), 
                    latex2exp::TeX(r'($\textbf{s.i}$)'), 
                    latex2exp::TeX(r'($\textbf{i.i}$)'), 
                    latex2exp::TeX(r'($\textbf{o.s}$)'), 
                    latex2exp::TeX(r'($\textbf{o.i}$)'), 
                    latex2exp::TeX(r'($\textbf{s.o}$)'),
                    latex2exp::TeX(r'($\textbf{i.o}$)'), 
                    latex2exp::TeX(r'($\textbf{o.o}$)')),
          col = "grey", 
          las = 1, 
          outline = T, 
          boxwex = 0.8, 
          horizontal = TRUE, 
          log = "x", 
          xlab = "(1 + gap)",
          main = latex2exp::TeX(r'(  \textbf{(6b)}  AIC – deviation from b.m.)'),
          cex.axis = 1.2,         
          cex.names = 1.2,
          cex.main = 1.3)
  
  #### Barplots of BIC ####
  
  par(mar = c(2.5, 2.5, 2, 1))
  table_BIC <- BIC(BIC_o_o, 
                   BIC_i_o, 
                   BIC_s_o, 
                   BIC_o_i, 
                   BIC_i_i, 
                   BIC_s_i, 
                   BIC_o_s, 
                   BIC_i_s, 
                   BIC_s_s)$table[c(9, 8, 7, 6, 5, 4, 3, 2, 1)]
  table_BIC <- table_BIC / r * 100
  barplot(table_BIC, names = c(latex2exp::TeX(r'($\textbf{s.s}$)'), 
                               latex2exp::TeX(r'($\textbf{i.s}$)'), 
                               latex2exp::TeX(r'($\textbf{s.i}$)'), 
                               latex2exp::TeX(r'($\textbf{i.i}$)'), 
                               latex2exp::TeX(r'($\textbf{o.s}$)'), 
                               latex2exp::TeX(r'($\textbf{o.i}$)'), 
                               latex2exp::TeX(r'($\textbf{s.o}$)'), 
                               latex2exp::TeX(r'($\textbf{i.o}$)'), 
                               latex2exp::TeX(r'($\textbf{o.o}$)')),
          col = "grey", 
          las = 1, 
          horiz = T,
          xlim = c(0, 100), 
          main = latex2exp::TeX(r'(\textbf{(7a)}  BIC – proportion as b.m. )'),
          cex.axis = 1.2,         
          cex.names = 1.2,
          cex.main = 1.3)
  box()
  
  #### Boxplots of BIC ####
  
  par(mar = c(2.5, 2.5, 2, 1.5))
  boxplot((1 + BIC(AIC_o_o, 
                   AIC_i_o, 
                   AIC_s_o, 
                   AIC_o_i, 
                   AIC_i_i, 
                   AIC_s_i, 
                   AIC_o_s, 
                   AIC_i_s, 
                   AIC_s_s)$delta[, c(9, 8, 7, 6, 5, 4, 3, 2, 1)]),
          names = c(latex2exp::TeX(r'($\textbf{s.s}$)'), 
                    latex2exp::TeX(r'($\textbf{i.s}$)'), 
                    latex2exp::TeX(r'($\textbf{s.i}$)'), 
                    latex2exp::TeX(r'($\textbf{i.i}$)'), 
                    latex2exp::TeX(r'($\textbf{o.s}$)'), 
                    latex2exp::TeX(r'($\textbf{o.i}$)'), 
                    latex2exp::TeX(r'($\textbf{s.o}$)'),
                    latex2exp::TeX(r'($\textbf{i.o}$)'), 
                    latex2exp::TeX(r'($\textbf{o.o}$)')),
          col = "grey", 
          las = 1, 
          outline = T, 
          boxwex = 0.8, 
          horizontal = TRUE, 
          log = "x", 
          xlab = "(1 + gap)",
          main = latex2exp::TeX(r'(  \textbf{(7b)}  BIC – deviation from b.m.)'),
          cex.axis = 1.2,         
          cex.names = 1.2,
          cex.main = 1.3)
}
```

$\sigma_A$: standard deviation of the variance-covariance matrix of intercept $A$

$\sigma_B$: standard deviation of the variance-covariance matrix of slope $B$

$\phi$: range of the variance-covariance matrix

$\nu$: smoothness parameter of the variance-covariance matrix

$m_X$: mean of the covariate $X$

unif, pois, sigma = 0.5, exp, C, phi = 0.015

```{r, fig.dim = c(9, 12.5), results="hide", message = FALSE, echo = FALSE, warning = FALSE}
plot_results('/Users/arthur/Desktop/R2/sigma=0.5/exp/C/0.015/results_to_plot.RData', 0.5, 0.015)
```
